# Generated by Django 4.1.6 on 2023-02-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mispeliculas', '0002_documentales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peliculas',
            new_name='Pelicula',
        ),
    ]
